language: ruby

services:
  - postgresql

rvm: 
  - 2.7.1 

script:
  - bundle update --bundler
  - bundle exec rake db:migrate
  - bundle exec rspec spec
  - bundle exec cucumber

before_script:
  - cp config/database.yml config/database.travis.yml
  - psql -c "create database IF NOT EXISTS development;"
  - psql -c "create database IF NOT EXISTS test;" 
  - psql -c "create database IF NOT EXISTS production;"


branches:
  only:
    - master
