development:
  adapter: postgresql
  database: engsi_database_development
  pool: 5
  timeout: 5000
  username: postgres
  password: c3po

test:
  adapter: postgresql
  database: engsi_database_test
  pool: 5
  timeout: 5000
  username: postgres
  password: c3po

production:
  adapter: postgresql
  database: engsi_database_production
  pool: 5
  timeout: 5000
  username: superuser
  password: