default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: engsi_database_development


test: &test
  <<: *default
  database: engsi_database_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
